/*
  +----------------------------------------------------------------------+
  | ort                                                                  |
  +----------------------------------------------------------------------+
  | Copyright (c) Joe Watkins 2025                                       |
  +----------------------------------------------------------------------+
  | This source file is subject to version 3.01 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available through the world-wide-web at the following url:           |
  | http://www.php.net/license/3_01.txt                                  |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Author: krakjoe                                                      |
  +----------------------------------------------------------------------+
 */
#ifndef HAVE_ORT_MATHS_SCHEMA_COS
#define HAVE_ORT_MATHS_SCHEMA_COS

#include "maths/promotion.h"

/* {{{
@extract %python% %extract.py% -f cos -n cos -u -w }}} */

static const ONNXTensorElementDataType ort_math_promotion_schema_table_cos[11] = {
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,	// cos(float16) -> float16
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,	// cos(float32) -> float32
    ONNX_TENSOR_ELEMENT_DATA_TYPE_DOUBLE,	// cos(float64) -> float64
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,	// cos(int8) -> float16
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,	// cos(int16) -> float32
    ONNX_TENSOR_ELEMENT_DATA_TYPE_DOUBLE,	// cos(int32) -> float64
    ONNX_TENSOR_ELEMENT_DATA_TYPE_DOUBLE,	// cos(int64) -> float64
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,	// cos(uint8) -> float16
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,	// cos(uint16) -> float32
    ONNX_TENSOR_ELEMENT_DATA_TYPE_DOUBLE,	// cos(uint32) -> float64
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,	// cos(bool) -> float16
};

static const ONNXTensorElementDataType ort_math_promotion_schema_indices_cos[11] = {
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_DOUBLE,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT8,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT16,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT32,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT8,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT16,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT32,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL,
};

static const ort_math_promotion_schema_t ort_math_promotion_schema_cos = {
    .kind     = ORT_MATH_PROMOTION_SCHEMA_KIND_UNARY,
    .operands = ORT_MATH_PROMOTION_SCHEMA_OPERANDS_PROMOTE,
    .table    = ort_math_promotion_schema_table_cos,
    .indices  = ort_math_promotion_schema_indices_cos,
    .size     = 11
};

/* {{{
    !!THIS FILE IS AUTOMATICALLY GENERATED: DO NOT EDIT!!
}}} */
#endif