/*
  +----------------------------------------------------------------------+
  | ort                                                                  |
  +----------------------------------------------------------------------+
  | Copyright (c) Joe Watkins 2025                                       |
  +----------------------------------------------------------------------+
  | This source file is subject to version 3.01 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available through the world-wide-web at the following url:           |
  | http://www.php.net/license/3_01.txt                                  |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Author: krakjoe                                                      |
  +----------------------------------------------------------------------+
 */
#ifndef HAVE_ORT_MATHS_SCHEMA_ROUND
#define HAVE_ORT_MATHS_SCHEMA_ROUND

#include "maths/promotion.h"

/* {{{
@extract %python% %extract.py% -f round -n round -u -w }}} */

static const ONNXTensorElementDataType ort_math_promotion_schema_table_round[11] = {
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,	// round(float16) -> float16
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,	// round(float32) -> float32
    ONNX_TENSOR_ELEMENT_DATA_TYPE_DOUBLE,	// round(float64) -> float64
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT8,	// round(int8) -> int8
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT16,	// round(int16) -> int16
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT32,	// round(int32) -> int32
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64,	// round(int64) -> int64
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT8,	// round(uint8) -> uint8
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT16,	// round(uint16) -> uint16
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT32,	// round(uint32) -> uint32
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,	// round(bool) -> float16
};

static const ONNXTensorElementDataType ort_math_promotion_schema_indices_round[11] = {
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_DOUBLE,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT8,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT16,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT32,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT8,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT16,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT32,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL,
};

static const ort_math_promotion_schema_t ort_math_promotion_schema_round = {
    .kind     = ORT_MATH_PROMOTION_SCHEMA_KIND_UNARY,
    .operands = ORT_MATH_PROMOTION_SCHEMA_OPERANDS_PROMOTE,
    .table    = ort_math_promotion_schema_table_round,
    .indices  = ort_math_promotion_schema_indices_round,
    .size     = 11
};

/* {{{
    !!THIS FILE IS AUTOMATICALLY GENERATED: DO NOT EDIT!!
}}} */
#endif