/*
  +----------------------------------------------------------------------+
  | ort                                                                  |
  +----------------------------------------------------------------------+
  | Copyright (c) Joe Watkins 2025                                       |
  +----------------------------------------------------------------------+
  | This source file is subject to version 3.01 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available through the world-wide-web at the following url:           |
  | http://www.php.net/license/3_01.txt                                  |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Author: krakjoe                                                      |
  +----------------------------------------------------------------------+
 */
#ifndef HAVE_ORT_MATHS_SCHEMA_SIGN
#define HAVE_ORT_MATHS_SCHEMA_SIGN

#include "maths/promotion.h"

/* {{{
@extract %python% %extract.py% -f sign -n sign -u -w }}} */

static const ONNXTensorElementDataType ort_math_promotion_schema_table_sign[11] = {
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16,	// sign(float16) -> float16
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT32,	// sign(float32) -> float32
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT64,	// sign(float64) -> float64
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT8,	// sign(int8) -> int8
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT16,	// sign(int16) -> int16
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT32,	// sign(int32) -> int32
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64,	// sign(int64) -> int64
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT8,	// sign(uint8) -> uint8
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT16,	// sign(uint16) -> uint16
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT32,	// sign(uint32) -> uint32
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UNDEFINED,	// sign(bool) -> UNDEFINED
};

static const ONNXTensorElementDataType ort_math_promotion_schema_indices_sign[11] = {
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT32,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT64,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT8,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT16,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT32,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT8,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT16,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT32,
    ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL,
};

static const ort_math_promotion_schema_t ort_math_promotion_schema_sign = {
    .kind     = ORT_MATH_PROMOTION_SCHEMA_KIND_UNARY,
    .operands = ORT_MATH_PROMOTION_SCHEMA_OPERANDS_PROMOTE,
    .table    = ort_math_promotion_schema_table_sign,
    .indices  = ort_math_promotion_schema_indices_sign,
    .size     = 11
};

/* {{{
    !!THIS FILE IS AUTOMATICALLY GENERATED: DO NOT EDIT!!
}}} */
#endif