name: Multi-arch CI

on:
  workflow_dispatch:

jobs:
  Install:
    runs-on: ${{ matrix.arch }}
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5', '8.6']
        arch: [arm64, riscv64]
        backend: [neon, none, riscv64]
        exclude:
          # Exclude neon from riscv64
          - arch: riscv64
            backend: neon
          # Exclude riscv64 backend from arm64
          - arch: arm64
            backend: riscv64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          /opt/php/${{ matrix.php }}/bin/phpize
          ./configure \
            --with-php-config=/opt/php/${{ matrix.php }}/bin/php-config \
            --enable-ort-backend=${{ matrix.backend }} \
            ${{ matrix.arch == 'arm64' && '--with-ort-onnx' || '' }}
          make -j$(nproc)
          sudo make install

      - name: Run Tests
        run: |
          make test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: tests-${{ matrix.arch }}-${{ matrix.backend }}-${{ matrix.php }}
          path: tests/

  Coverage:
    runs-on: ${{ matrix.arch }}
    continue-on-error: true
    needs: [Install]

    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5', '8.6']
        arch: [arm64, riscv64]
        backend: [neon, none, riscv64]
        exclude:
          - arch: riscv64
            backend: neon
          - arch: arm64
            backend: riscv64

    steps:
      - name: Run Coverage
        run: |
          ORT_SCALE_CORES=1 make ort-test-coverage-html

      - name: Upload HTML Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.arch }}-${{ matrix.backend }}-${{ matrix.php }}
          path: html/

      - name: Send Coveralls Report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage.info
          flag-name: ${{ matrix.arch }}-${{ matrix.backend }}-${{ matrix.php }}
          parallel: true

  Finish:
    if: always()
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [Coverage]
    steps:
    - name: Finish Coveralls Reporting
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true