name: Multi-arch CI

on:
  workflow_dispatch:

jobs:
  arm64-install:
    runs-on: arm64
    continue-on-error: true
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5', '8.6']
        backend: [neon, none]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            clean: true
        
      - name: Build
        run: |
          /opt/php/${{ matrix.php }}/bin/phpize
          ./configure \
            --with-php-config=/opt/php/${{ matrix.php }}/bin/php-config \
            --enable-ort-backend=${{ matrix.backend }} \
            --with-ort-onnx
          make -j$(nproc)
          sudo make install

      - name: Run Tests
        run: |
          TEST_PHP_ARGS=--show-diff make test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: tests-arm64-${{ matrix.backend }}-${{ matrix.php }}
          path: tests/

  arm64-coverage:
    if: success() || failure()
    runs-on: arm64
    continue-on-error: true
    needs: [arm64-install]

    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5', '8.6']
        backend: [neon, none]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            clean: true
        
      - name: Build
        run: |
          /opt/php/${{ matrix.php }}/bin/phpize
          ./configure \
            --with-php-config=/opt/php/${{ matrix.php }}/bin/php-config \
            --enable-ort-backend=${{ matrix.backend }} \
            --with-ort-onnx
          make -j$(nproc)
          sudo make install

      - name: Run Coverage
        run: |
          ORT_SCALE_CORES=1 make ort-test-coverage-html

      - name: Upload HTML Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-arm64-${{ matrix.backend }}-${{ matrix.php }}
          path: html/

      - name: Send Coveralls Report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage.info
          flag-name: arm64-${{ matrix.backend }}-${{ matrix.php }}
          parallel: true

  riscv64-install:
    runs-on: riscv64
    continue-on-error: true
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5', '8.6']
        backend: [riscv64, none]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            clean: true

      - name: Build
        run: |
          /opt/php/${{ matrix.php }}/bin/phpize
          ./configure \
            --with-php-config=/opt/php/${{ matrix.php }}/bin/php-config \
            --enable-ort-backend=${{ matrix.backend }}
          make -j$(nproc)
          sudo make install

      - name: Run Tests
        run: |
          TEST_PHP_ARGS=--show-diff make test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: tests-riscv64-${{ matrix.backend }}-${{ matrix.php }}
          path: tests/

  riscv64-coverage:
    if: success() || failure()
    runs-on: riscv64
    continue-on-error: true
    needs: [riscv64-install]

    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5', '8.6']
        backend: [riscv64, none]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            clean: true

      - name: Build
        run: |
          /opt/php/${{ matrix.php }}/bin/phpize
          ./configure \
            --with-php-config=/opt/php/${{ matrix.php }}/bin/php-config \
            --enable-ort-backend=${{ matrix.backend }}
          make -j$(nproc)
          sudo make install

      - name: Run Coverage
        run: |
          ORT_SCALE_CORES=1 make ort-test-coverage-html

      - name: Upload HTML Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-riscv64-${{ matrix.backend }}-${{ matrix.php }}
          path: html/

      - name: Send Coveralls Report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage.info
          flag-name: riscv64-${{ matrix.backend }}-${{ matrix.php }}
          parallel: true

  x64-install:
    runs-on: x64
    continue-on-error: true
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5', '8.6']
        backend: [avx2, sse41, sse2, none]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            clean: true

      - name: Build
        run: |
          /opt/php/${{ matrix.php }}/bin/phpize
          ./configure \
            --with-php-config=/opt/php/${{ matrix.php }}/bin/php-config \
            --enable-ort-backend=${{ matrix.backend }} \
            --with-ort-onnx
          make -j$(nproc)
          sudo make install

      - name: Run Tests
        run: |
          TEST_PHP_ARGS=--show-diff make test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: tests-x64-${{ matrix.backend }}-${{ matrix.php }}
          path: tests/

  x64-coverage:
    if: success() || failure()
    runs-on: x64
    continue-on-error: true
    needs: [x64-install]

    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5', '8.6']
        backend: [avx2, sse41, sse2, none]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            clean: true

      - name: Build
        run: |
          /opt/php/${{ matrix.php }}/bin/phpize
          ./configure \
            --with-php-config=/opt/php/${{ matrix.php }}/bin/php-config \
            --enable-ort-backend=${{ matrix.backend }} \
            --with-ort-onnx
          make -j$(nproc)
          sudo make install

      - name: Run Coverage
        run: |
          ORT_SCALE_CORES=1 make ort-test-coverage-html

      - name: Upload HTML Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-x64-${{ matrix.backend }}-${{ matrix.php }}
          path: html/

      - name: Send Coveralls Report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage.info
          flag-name: x64-${{ matrix.backend }}-${{ matrix.php }}
          parallel: true

  finish:
    if: success() || failure()
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [arm64-coverage, riscv64-coverage, x64-coverage]
    steps:
    - name: Finish Coveralls Reporting
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true