name: pages

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: php-ort

      - name: Checkout PHP source
        uses: actions/checkout@v4
        with:
          repository: php/php-src
          ref: PHP-8.2  # Or whatever version you're using
          path: php-src

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: 4.0.11

      - name: Cache Emscripten
        uses: actions/cache@v3
        with:
          path: ~/.emscripten_cache
          key: ${{ runner.os }}-emscripten-${{ hashFiles('**/dist/emsdk.build') }}

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison re2c autoconf pkg-config

      - name: Copy extension to PHP
        run: |
          cp -r php-ort php-src/ext/ort

      - name: Copy emsdk to PHP
        run: |
          cp php-ort/dist/emsdk/* php-src

      - name: Build php-em.wasm
        run: |
          cd php-src && EM_EXTRA_CONFIGURE=--enable-ort=static make -f emsdk.mk

      - name: Copy artifacts to dist
        run: |
          cp php-src/php-em.{js,wasm} php-ort/dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload dist as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: php-ort/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4