name: pages

on:
  workflow_run:
    workflows: ["Testing"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: php-ort

      - name: Checkout PHP source
        uses: actions/checkout@v4
        with:
          repository: php/php-src
          ref: PHP-8.4
          path: php-src

      - name: Copy extension to PHP
        run: |
          cp -r php-ort php-src/ext/ort

      - name: Build em
        id: build-em
        uses: krakjoe/em@develop
        with:
          EM_PHP_DIR: ./php-src
          EM_PHP_CONFIGURE: --enable-ort=static
          with: >
            ctype zlib bz2 sqlite3 pdo pdo-sqlite
            phar mbstring calendar bcmath opcache

      - name: Copy em to dist
        run: |
          cp php-em.{js,wasm} php-ort/dist/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload dist as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: php-ort/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4