name: riscv64

on:
  workflow_dispatch:

jobs:
  Install:
    runs-on: riscv64
    strategy:
      matrix:
        php: [ '8.2', '8.3', '8.4', '8.5', '8.6' ]
        backend:
          - riscv64
          - none

    steps:
      - name: Debug
        run: |
          echo "GitHub runner.arch: '${{ runner.arch }}'"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          /opt/php/${{ matrix.php }}/bin/phpize
          ./configure --with-php-config=/opt/php/${{ matrix.php }}/bin/php-config --enable-ort-backend=${{ matrix.backend }}
          make -j$(nproc)
          sudo make install

      - name: Run Tests
        run: |
          TEST_PHP_EXECUTABLE=/opt/php/${{ matrix.php }}/bin/php make test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: tests-php${{ matrix.php }}-${{ matrix.backend }}
          path: tests/
  Coverage:
    runs-on: riscv64
    needs: [Install]

    strategy:
      matrix:
        php: [ '8.2', '8.3', '8.4', '8.5', '8.6' ]
        backend:
          - riscv64
          - none

    steps:
      - name: Run Coverage
        run: |
          ORT_SCALE_CORES=1 TEST_PHP_EXECUTABLE=/opt/php/${{ matrix.php }}/bin/php make ort-test-coverage-html

      - name: Upload HTML Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-php-${{ matrix.php }}-backend-${{ matrix.backend }}
          path: html/

      - name: Send Coveralls Report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage.info
          flag-name: backend-${{ matrix.backend }}
          parallel: true
  Finish:
    if: always()
    runs-on: riscv64
    continue-on-error: true
    needs: [Coverage]
    steps:
    - name: Finish Coveralls Reporting
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
        carryforward: "backend-none, backend-riscv64"
