name: riscv64

on:
  workflow_dispatch:

jobs:
  RunBasicTests:
    runs-on: [self-hosted, linux, riscv64]
    strategy:
      matrix:
        php: [ '8.2', '8.3', '8.4', '8.5', '8.6' ]
        backend:
          - none
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential re2c autoconf pkg-config lcov gcc
          sudo ldconfig
      - name: Install Extension
        run: |
          phpize
          case "${{ matrix.backend }}" in
            none)
              ./configure --disable-ort-backend
              ;;
          esac
          make -j$(nproc)
          sudo make install

      - name: Run Tests
        run: |
          make test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: tests-php${{ matrix.php }}-${{ matrix.backend }}
          path: tests/
  BuildCoverallsReport:
    runs-on: [self-hosted, linux, riscv64]
    needs: [RunBasicTests]

    strategy:
      matrix:
        php: [ '8.2', '8.3', '8.4', '8.5', '8.6' ]
        backend:
          - none

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential re2c autoconf pkg-config lcov gcc
          sudo ldconfig
      - name: Install Extension
        run: |
          phpize
          case "${{ matrix.backend }}" in
            none)
              ./configure --disable-ort-backend
              ;;
          esac
          make -j$(nproc)
          sudo make install

      - name: Run Coverage
        run: |
          ORT_SCALE_CORES=1 make ort-test-coverage-html

      - name: Upload HTML Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-php-${{ matrix.php }}-backend-${{ matrix.backend }}
          path: html/

      - name: Send Coveralls Report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage.info
          flag-name: backend-${{ matrix.backend }}
          parallel: true
  FinishCoverallsReport:
    if: always()
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [BuildCoverallsReport]
    steps:
    - name: Finish Coveralls Reporting
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
        carryforward: "backend-none"
